var abi = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  {
    anonymous: !1,
    inputs: [
      { indexed: !0, internalType: 'address', name: 'owner', type: 'address' },
      {
        indexed: !0,
        internalType: 'address',
        name: 'approved',
        type: 'address',
      },
      {
        indexed: !0,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: !1,
    inputs: [
      { indexed: !0, internalType: 'address', name: 'owner', type: 'address' },
      {
        indexed: !0,
        internalType: 'address',
        name: 'operator',
        type: 'address',
      },
      { indexed: !1, internalType: 'bool', name: 'approved', type: 'bool' },
    ],
    name: 'ApprovalForAll',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: '_t', type: 'address' },
      { internalType: 'uint256', name: '_c', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_a', type: 'address' }],
    name: 'ATTACK',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_a', type: 'address' }],
    name: 'CLAIM',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_i', type: 'uint256' }],
    name: 'MINT',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_f', type: 'address' },
      { internalType: 'address', name: '_t', type: 'address' },
      { internalType: 'uint256', name: '_c', type: 'uint256' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_f', type: 'address' },
      { internalType: 'address', name: '_t', type: 'address' },
      { internalType: 'uint256', name: '_c', type: 'uint256' },
      { internalType: 'bytes', name: '_d', type: 'bytes' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_i', type: 'uint256' },
      { internalType: 'uint256', name: '_l', type: 'uint256' },
      { internalType: 'string', name: '_c', type: 'string' },
    ],
    name: 'setURI',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_a', type: 'address' }],
    name: 'TokenAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    anonymous: !1,
    inputs: [
      { indexed: !0, internalType: 'address', name: 'from', type: 'address' },
      { indexed: !0, internalType: 'address', name: 'to', type: 'address' },
      {
        indexed: !0,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'Transfer',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: '_f', type: 'address' },
      { internalType: 'address', name: '_t', type: 'address' },
      { internalType: 'uint256', name: '_c', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_c', type: 'uint256' }],
    name: 'getApproved',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'nft',
    outputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'uint256', name: 'item', type: 'uint256' },
      { internalType: 'uint256', name: 'level', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_c', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'player',
    outputs: [
      { internalType: 'uint256', name: 'wood', type: 'uint256' },
      { internalType: 'uint256', name: 'metal', type: 'uint256' },
      { internalType: 'uint256', name: 'food', type: 'uint256' },
      { internalType: 'uint256', name: 'owl', type: 'uint256' },
      { internalType: 'uint256', name: 'soldier', type: 'uint256' },
      { internalType: 'uint256', name: 'balance', type: 'uint256' },
      { internalType: 'uint256', name: 'lastClaimed', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_a', type: 'address' }],
    name: 'PLAYERITEMS',
    outputs: [
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: '_t', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_c', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
];
